spring:
  name:
    application: portaria-projeto


  #config banco de dados
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:65432/portaria
    username: postgres
    password: 123456

  #config JPA + hibarnate
  jpa:
    hibernate:
      ddl-auto: update # atualiza banco
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true




server:
  port: 8080