version: '3'


services:

  postgres-compose:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "root"
    ports:
      - "65432:5432"
    volumes:
      - biblioteca-postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network



networks:
  postgres-compose-network:
    driver: bridge
volumes:
  biblioteca-postgres-data:
