CREATE TABLE IF NOT EXISTS MORADORES (

    cpf VARCHAR(11) NOT NULL UNIQUE,
    nome VARCHAR(100) NOT NULL,
    id_morador int NOT NULL,

    FOREIGN KEY (id_morador) REFERENCES MORADORES(id) ON UPDATE CASCADE ON DELETE CASCADE

);